### ISSUE TITLE
Some manpages are missing

### ISSUE THREAD

**Issue by bobjolliffe** [dhis2/dhis2-tools#10]
W: dhis2-tools: binary-without-manpage usr/bin/dhis2-backup
W: dhis2-tools: binary-without-manpage usr/bin/dhis2-integrity
W: dhis2-tools: binary-without-manpage usr/bin/dhis2-nginx
W: dhis2-tools: binary-without-manpage usr/bin/dhis2-restoredb

**Comment by simjes** [comment]
Fixed in cd14c97
