### ISSUE TITLE
Makepasswd does not work on certain VMs causing DHIS2 tools to hang. 

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dhis2-tools#30]
https://unix.stackexchange.com/questions/319614/makepasswd-not-working-properly-in-debian-stretch

`sudo apt-get install haveged` seemed to solve the problem for me.

**Comment by bobjolliffe** [comment]
Makepasswd was replaced some years back by "openssl rand ..." which is much more reliable.
