### ISSUE TITLE
Oracle Java (JDK) 8 Installer PPA (DISCONTINUED)

### ISSUE THREAD

**Issue by prcleary** [dhis2/dhis2-tools#33]
See https://launchpad.net/~webupd8team/+archive/ubuntu/java 

Currently DHIS 2 Tools install.sh script will fail with "package 'oracle-java8-installer' has no installation candidate"

Can we use other versions of Java?

**Comment by bobjolliffe** [comment]
Good point Paul.  I have fixed the example install script to use openjdk-8 instead.  Note that the package itself has no hard jvm dependency.
