### ISSUE TITLE
Nginx default settings are insecure

### ISSUE THREAD

**Issue by bobjolliffe** [dhis2/dhis2-tools#5]
The default ssl settings if you use dhis2-nginx need to be updated.

Question:  should dhis2-nginx remain part of the package at all?

**Comment by simjes** [comment]
Updated sample config for Nginx and made some echo noise when using the script. It informs the user about ssl and points to the letsencrypt guide. Still think dhis2-nginx is handy. 84790d3e8aa2d05623a7dfa0a41532dd8bb4a82d

Continue discussion in #13.
