### ISSUE TITLE
support dhis.conf

### ISSUE THREAD

**Issue by bobjolliffe** [dhis2/dhis2-tools#8]
By default tools generate hibernate.properties.  Need to upgrade support for dhis.conf, including database encryption target

**Comment by grelland** [comment]
This needs to happen ASAP as hibernate.properties is not supported as of current 2.25-SNAPSHOT and going forward. The problem already broke a test server for the Android guys (and caused a medium scale headache).

Documentation for dhis.conf is found [here](http://dhis2.github.io/dhis2-docs/master/en/implementer/html/install_server_setup.html)

**Comment by simjes** [comment]
fixed in 1c553efbdad7b9bcadf1d128d3d5bd0903d6d43d
